name: Build and Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      node-version: [16]
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@latest
        with:
          version: 7

      - name: Use Node.js ${{ node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
